version: '3'
services:
  backend:
    build: .
    ports:
      - "8768:8768"
    volumes:
      - ./backend:/app/backend
      - ./config:/app/config
    env_file:
      - ./config/.env
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "8100:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always